In [1]:
import pandas as pd
import numpy as np

In [2]:
chd = pd.read_csv('CHDdata.csv')
chd.head(3)

   sbp  tobacco   ldl  adiposity  famhist  typea  obesity  alcohol  age  chd
0  160    12.00  5.73      23.11  Present     49    25.30    97.20   52    1
1  144     0.01  4.41      28.61   Absent     55    28.87     2.06   63    1
2  118     0.08  3.48      32.28  Present     52    29.14     3.81   46    0

In [45]:
chd.shape

(462, 10)

In [3]:
cont_columns = ['sbp', 'tobacco', 'ldl', 'adiposity', 'typea', 'obesity', 'alcohol', 'age']

In [4]:
for column in cont_columns:
    X = chd[[column]]
    mu = chd[[column]].mean()
    sd = chd[[column]].std()
    chd[column] = (X - mu) / sd
chd.head()

,sbp,tobacco,ldl,adiposity,famhist,typea,obesity,alcohol,age,chd
0,1.057417,1.821099,0.477894,-0.295183,Present,-0.418017,-0.176594,3.274189,0.628654,1
1,0.276789,-0.789382,-0.159507,0.411694,Absent,0.193134,0.670646,-0.612081,1.381617,1
2,-0.991731,-0.774141,-0.608585,0.883374,Present,-0.112441,0.734723,-0.540597,0.217947,0
3,1.545310,0.841352,0.806252,1.622382,Present,-0.214300,1.411091,0.294742,1.039361,1
4,-0.211103,2.169453,-0.598928,0.305020,Present,0.702427,-0.012842,1.645991,0.423301,1

In [5]:
chd_no = chd[chd['chd'] == 0]
chd_yes = chd[chd['chd'] == 1]
chd_no

,sbp,tobacco,ldl,adiposity,famhist,typea,obesity,alcohol,age,chd
2,-0.991731,-0.774141,-0.608585,0.883374,Present,-0.112441,0.734723,-0.540597,0.217947,0
5,-0.308682,0.558314,0.835225,1.388470,Present,0.906144,1.121558,-0.118638,0.149496,0
6,0.179211,0.090213,-0.656873,-1.183278,Absent,0.600569,-1.242171,-0.589206,-0.329662,0
8,-1.186888,-0.791559,-0.439577,-0.772004,Present,-0.418017,-0.281016,-0.594517,-0.945722,0
12,-0.991731,-0.791559,-1.381193,-1.973696,Absent,0.600569,-1.061806,-0.696228,-1.767136,0
...,...,...,...,...,...,...,...,...,...,...
452,0.764682,0.412441,-0.743792,0.437399,Present,0.804286,0.025129,1.051654,-0.055857,0
456,1.545310,-0.704470,-0.304371,2.140331,Present,0.294993,1.674519,-0.612081,0.970910,0
457,3.692037,-0.704470,0.598614,0.811401,Absent,1.109862,0.570971,-0.696228,1.039361,0
459,-1.479624,-0.138395,-1.521228,-1.307946,Absent,-1.334744,-1.413043,0.391960,0.834008,0
460,-0.991731,0.384137,3.317227,0.691875,Absent,1.109862,0.309916,0.282897,-0.192760,0

In [6]:
chd_yes

,sbp,tobacco,ldl,adiposity,famhist,typea,obesity,alcohol,age,chd
0,1.057417,1.821099,0.477894,-0.295183,Present,-0.418017,-0.176594,3.274189,0.628654,1
1,0.276789,-0.789382,-0.159507,0.411694,Absent,0.193134,0.670646,-0.612081,1.381617,1
3,1.545310,0.841352,0.806252,1.622382,Present,-0.214300,1.411091,0.294742,1.039361,1
4,-0.211103,2.169453,-0.598928,0.305020,Present,0.702427,-0.012842,1.645991,0.423301,1
7,-1.186888,0.096745,-0.072589,-1.388915,Present,0.906144,-0.696330,-0.421730,1.039361,1
...,...,...,...,...,...,...,...,...,...,...
453,-0.698996,-0.443205,1.197385,1.834446,Present,-1.742178,1.294803,-0.696228,0.560203,1
454,0.374368,-0.652217,0.038474,0.335866,Absent,0.702427,0.490281,-0.360050,-0.261211,1
455,-0.503839,-0.303863,-0.922457,0.137940,Absent,-0.519876,-0.494606,1.240780,-1.082625,1
458,2.130781,0.122871,-0.159507,0.860240,Absent,-0.112441,0.608942,0.068445,0.628654,1
461,-0.308682,-0.791559,0.038474,1.028605,Present,0.906144,-2.692210,-0.696228,0.217947,1

## Without CHD:

prior ~ $N(\mu_0, vw^-1)$

In [11]:
mu_zero = np.array([0] * 8)#.reshape(8,1)
mu_zero

array([0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
variance = np.array([1] * 8)
variance

array([1, 1, 1, 1, 1, 1, 1, 1])

In [13]:
x_bar = np.array([])

for column in cont_columns:
    mean = chd_no[[column]].mean()
    x_bar = np.append(x_bar, mean)
#x_bar = x_bar.reshape(8,1)    
x_bar

array([-0.13985805, -0.21792053, -0.19126202, -0.1847682 , -0.0750032 ,
       -0.07277776, -0.0454652 , -0.27118382])

In [20]:
mu_post = (1 * mu_zero + 302 * x_bar) / (1 + 302)
#mu_post = mu_post.reshape(8,1)
mu_post

array([-0.13939647, -0.21720132, -0.19063079, -0.1841584 , -0.07475566,
       -0.07253757, -0.04531515, -0.27028883])

In [21]:
r_prior = np.zeros((8, 8), int)
np.fill_diagonal(r_prior, 1)
r_prior

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]])

In [22]:
X = np.matrix(chd_no[cont_columns])
X
print(X.shape)

(302, 8)

In [44]:
x_1 = X[:,0]
print(x_1)
print(X.shape)
print(x_1.shape)
print(x_bar[0].shape)
print((x_1 - x_bar[0]).shape)

[[-0.99173133]
 [-0.30868179]
 [ 0.17921074]
 [-1.18688834]
 [-0.99173133]
 [-0.30868179]
 [-1.28446684]
 [-1.04052058]
 [-0.89415282]
 [-0.30868179]
 [ 0.56952476]
 [-0.01594627]
 [ 0.17921074]
 [-0.99173133]
 [ 0.27678925]
 [ 0.47194626]
 [ 0.08163223]
 [-1.38204535]
 [-0.40626029]
 [ 0.27678925]
 [-0.89415282]
 [-1.18688834]
 [-0.5038388 ]
 [-1.18688834]
 [-0.6014173 ]
 [-0.79657432]
 [-0.21110328]
 [ 0.86226028]
 [ 0.66710327]
 [-0.99173133]
 [-1.72357012]
 [-0.84536357]
 [ 0.17921074]
 [-0.01594627]
 [ 0.66710327]
 [ 0.08163223]
 [-0.40626029]
 [-0.11352478]
 [-0.69899581]
 [-1.28446684]
 [-0.99173133]
 [-0.99173133]
 [-0.40626029]
 [-0.40626029]
 [-0.6014173 ]
 [-0.5038388 ]
 [-0.11352478]
 [-0.21110328]
 [-1.47962385]
 [-0.5038388 ]
 [-0.40626029]
 [ 0.08163223]
 [-0.6014173 ]
 [-0.79657432]
 [-1.08930983]
 [ 0.22799999]
 [ 2.71625189]
 [-0.21110328]
 [-0.01594627]
 [-0.11352478]
 [ 1.2525743 ]
 [-0.11352478]
 [ 1.35015281]
 [-0.99173133]
 [-0.5038388 ]
 [-0.99173133]
 [ 0.95983878]
 [-0.99173133]
 [-0.69899581]
 [-1.18688834]
 [-0.21110328]
 [-0.5038388 ]
 [ 0.76468177]
 [-0.40626029]
 [-0.5038388 ]
 [-0.89415282]
 [-0.89415282]
 [ 0.71589252]
 [ 0.47194626]
 [-0.11352478]
 [ 0.66710327]
 [ 0.95983878]
 [ 0.17921074]
 [-0.21110328]
 [-1.08930983]
 [-0.5038388 ]
 [-0.89415282]
 [-0.69899581]
 [-0.5038388 ]
 [-0.40626029]
 [-1.4308346 ]
 [ 0.27678925]
 [-0.99173133]
 [ 0.47194626]
 [-0.5038388 ]
 [-0.79657432]
 [-1.47962385]
 [-0.55262805]
 [ 1.74046683]
 [-0.79657432]
 [-0.6014173 ]
 [-0.01594627]
 [ 0.47194626]
 [-0.79657432]
 [-0.30868179]
 [-0.6014173 ]
 [ 1.1549958 ]
 [ 2.71625189]
 [-0.99173133]
 [-0.69899581]
 [ 1.05741729]
 [-0.5038388 ]
 [-0.30868179]
 [-0.89415282]
 [-0.5038388 ]
 [-1.47962385]
 [ 1.35015281]
 [ 0.66710327]
 [ 0.56952476]
 [-0.45504955]
 [-0.21110328]
 [-0.40626029]
 [-0.01594627]
 [-0.01594627]
 [-0.5038388 ]
 [ 1.1549958 ]
 [ 0.47194626]
 [-0.69899581]
 [-0.21110328]
 [-0.5038388 ]
 [-0.79657432]
 [ 0.66710327]
 [ 1.1549958 ]
 [-0.69899581]
 [-0.11352478]
 [-0.11352478]
 [-0.21110328]
 [-1.08930983]
 [-0.30868179]
 [-0.21110328]
 [-0.69899581]
 [-1.18688834]
 [ 3.39930142]
 [-0.01594627]
 [ 0.27678925]
 [-0.30868179]
 [ 0.22799999]
 [-0.11352478]
 [-0.79657432]
 [-0.01594627]
 [-0.6014173 ]
 [ 1.83804534]
 [-0.79657432]
 [-0.69899581]
 [-0.5038388 ]
 [ 2.52109487]
 [-0.5038388 ]
 [ 0.95983878]
 [ 1.05741729]
 [ 0.95983878]
 [-0.5038388 ]
 [ 0.37436775]
 [ 1.10620654]
 [ 0.17921074]
 [ 0.76468177]
 [-0.69899581]
 [-0.69899581]
 [-0.11352478]
 [-0.99173133]
 [-0.99173133]
 [-0.21110328]
 [-1.18688834]
 [-0.11352478]
 [ 0.76468177]
 [-0.69899581]
 [-1.18688834]
 [-0.99173133]
 [ 0.37436775]
 [-0.21110328]
 [-0.6014173 ]
 [-0.21110328]
 [-0.21110328]
 [-0.74778506]
 [-1.28446684]
 [-1.82114862]
 [ 0.56952476]
 [-0.21110328]
 [-0.30868179]
 [-0.11352478]
 [ 1.35015281]
 [-0.01594627]
 [ 1.54530982]
 [-0.11352478]
 [-0.5038388 ]
 [ 0.56952476]
 [ 0.17921074]
 [-0.40626029]
 [-1.18688834]
 [ 1.74046683]
 [ 2.52109487]
 [ 0.76468177]
 [-0.69899581]
 [-1.18688834]
 [ 0.17921074]
 [ 0.76468177]
 [ 0.37436775]
 [ 1.35015281]
 [-0.11352478]
 [-0.30868179]
 [-0.5038388 ]
 [-1.57720236]
 [ 0.27678925]
 [ 0.76468177]
 [-0.6014173 ]
 [ 1.1549958 ]
 [-0.01594627]
 [ 0.47194626]
 [-0.69899581]
 [-0.99173133]
 [-0.01594627]
 [-0.06473552]
 [-0.5038388 ]
 [ 1.1549958 ]
 [-0.89415282]
 [-0.11352478]
 [-0.79657432]
 [-0.21110328]
 [-0.11352478]
 [-0.30868179]
 [ 0.66710327]
 [-0.69899581]
 [ 0.08163223]
 [ 1.35015281]
 [-0.30868179]
 [ 0.56952476]
 [-0.21110328]
 [-0.6014173 ]
 [ 0.47194626]
 [-0.30868179]
 [-0.5038388 ]
 [-0.5038388 ]
 [ 0.08163223]
 [-0.6014173 ]
 [-1.18688834]
 [-0.99173133]
 [-0.6014173 ]
 [-1.28446684]
 [ 0.08163223]
 [-0.5038388 ]
 [-0.6014173 ]
 [ 0.27678925]
 [ 0.37436775]
 [ 1.93562384]
 [ 2.03320235]
 [-0.21110328]
 [ 0.17921074]
 [ 1.1549958 ]
 [-0.6014173 ]
 [-0.21110328]
 [-0.30868179]
 [ 1.05741729]
 [-1.08930983]
 [-1.28446684]
 [-0.89415282]
 [ 1.35015281]
 [ 0.37436775]
 [ 0.95983878]
 [ 1.83804534]
 [-0.30868179]
 [-0.6014173 ]
 [-0.89415282]
 [ 1.74046683]
 [-0.30868179]
 [ 0.17921074]
 [ 0.37436775]
 [-0.30868179]
 [-0.89415282]
 [-0.99173133]
 [-1.47962385]
 [-0.11352478]
 [-0.89415282]
 [-0.30868179]
 [-0.11352478]
 [-0.01594627]
 [-0.01594627]
 [-0.40626029]
 [-0.40626029]
 [-1.38204535]
 [-0.89415282]
 [ 1.35015281]
 [-0.21110328]
 [ 0.17921074]
 [-0.11352478]
 [-0.40626029]
 [-0.69899581]
 [-0.11352478]
 [-0.89415282]
 [ 0.76468177]
 [ 1.54530982]
 [ 3.69203694]
 [-1.47962385]
 [-0.99173133]]
(302, 8)
(302, 1)
()
(302, 1)

In [43]:
inside = (x_1 - x_bar[0]) @ (x_1 - x_bar[0]).T
print(inside.shape)

(302, 302)

In [38]:
s = (x_1 - x_bar[0]) @ (x_1 - x_bar[0]).T
a

matrix([[ 0.72568808,  0.14381643, -0.27180618, ..., -3.26428895,
          1.14131069,  0.72568808],
        [ 0.14381643,  0.02850145, -0.05386639, ..., -0.64691484,
          0.22618427,  0.14381643],
        [-0.27180618, -0.05386639,  0.10180489, ...,  1.22263809,
         -0.42747745, -0.27180618],
        ...,
        [-3.26428895, -0.64691484,  1.22263809, ..., 14.68341921,
         -5.13384188, -3.26428895],
        [ 1.14131069,  0.22618427, -0.42747745, ..., -5.13384188,
          1.79497241,  1.14131069],
        [ 0.72568808,  0.14381643, -0.27180618, ..., -3.26428895,
          1.14131069,  0.72568808]])

In [39]:
print(a.shape)

(302, 302)

In [34]:
a = (mu_zero - x_bar).reshape(8,1)

In [36]:
b = (1 * 302 / (1+302)) * a @ a.T
b
print(b.shape)

(8, 8)

In [26]:
no_chd = pd.DataFrame({'mu_zero': mu_zero, 'variance': variance,'x_bar': x_bar, 'mu_post': mu_post})
no_chd.index = cont_columns
no_chd

           mu_zero  variance     x_bar   mu_post
sbp              0         1 -0.139858 -0.139396
tobacco          0         1 -0.217921 -0.217201
ldl              0         1 -0.191262 -0.190631
adiposity        0         1 -0.184768 -0.184158
typea            0         1 -0.075003 -0.074756
obesity          0         1 -0.072778 -0.072538
alcohol          0         1 -0.045465 -0.045315
age              0         1 -0.271184 -0.270289

## With CHD:

prior ~ $N(\mu_0, \dfrac{1}{\tau_0 w}) = N(0, \frac{1}{302})$

In [16]:
x_bar = np.array([])

for column in cont_columns:
    mean = chd_yes[[column]].mean()
    x_bar = np.append(x_bar, mean)
    
x_bar

array([0.26398207, 0.411325  , 0.36100706, 0.34874997, 0.14156853,
       0.13736803, 0.08581557, 0.51185947])

In [17]:
mu_post = (1 * mu_zero + 160 * x_bar) / (1 + 160)
mu_post

array([0.26234243, 0.40877019, 0.35876478, 0.34658382, 0.14068922,
       0.13651481, 0.08528256, 0.50868022])

In [18]:
s =

SyntaxError: invalid syntax (<ipython-input-18-063da17ce760>, line 1)

In [ ]:
yes_chd = pd.DataFrame({'mu_zero': mu_zero, 'variance': variance,'x_bar': x_bar, 'mu_post': mu_post})
yes_chd.index = cont_columns
yes_chd